### ISSUE TITLE
Set up PyPI auto-deploy on verified release (tag)

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete#32]

**Comment by pasuder** [comment]
CodeShip could be used for that. Or any other CI which could be integrated with that GitHub repository.

Links:

- https://docs.travis-ci.com/user/deployment/pypi/
- https://github.com/pypa/twine

I will test it later with my own repository/account.

**Comment by pasuder** [comment]
Before PyPi, you can also have releases on GitHub automatically uploaded from Travis:

```yaml
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  on:
    tags: true
```

More info here: https://docs.travis-ci.com/user/deployment/releases/

It will work when tag is pushed to repo on any commit.
